#pragma config(Sensor, in1,    pot,            sensorPotentiometer)
#pragma config(Sensor, in2,    pPowerExp,      sensorAnalog)
#pragma config(Sensor, in3,    gyro,           sensorGyro)
#pragma config(Sensor, in4,    acX,            sensorAccelerometer)
#pragma config(Sensor, in5,    acY,            sensorAccelerometer)
#pragma config(Sensor, dgtl12, initIndicator,  sensorLEDtoVCC)
#pragma config(Motor,  port1,           lFront,        tmotorVex393TurboSpeed_HBridge, openLoop)
#pragma config(Motor,  port2,           lMid,          tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           lBack,         tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port4,           tetherLMid,    tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           tetherLY,      tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port6,           tetherRMid,    tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port7,           tetherRY,      tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           rBack,         tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           rMid,          tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port10,          rFront,        tmotorVex393TurboSpeed_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{



}
