#pragma config(UserModel, "C:/Users/rstudent/code/39a-starstruck/tetherBotConfig.c")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX2)
#pragma competitionControl(Competition)
#include "Vex_Competition_Includes.c"
#include <CKVexMotorSet.h>

MotorSet driveMainLeft;
tMotor mainDriveMotorsLeft[] = {lFront, lMid, lBack};

MotorSet driveMainRight;
tMotor mainDriveMotorsRight[] = {rFront, rMid, rBack};

MotorSet driveTetherRight;
tMotor tetherDriveMotorsRight[] = {tetherRMid, tetherRY};

MotorSet driveTetherLeft;
tMotor tetherDriveMotorsLeft[] = {tetherLMid, tetherLY};

void pre_auton()
{
  bStopTasksBetweenModes = true;
  MotorSetInit (driveMainLeft, mainDriveMotorsLeft, 3);
  MotorSetInit (driveMainRight, mainDriveMotorsRight, 3);
  MotorSetInit (driveTetherLeft, tetherDriveMotorsLeft, 2);
  MotorSetInit (driveTetherRight, tetherDriveMotorsRight, 2);
}

task autonomous()
{
  AutonomousCodePlaceholderForTesting();
}

task usercontrol()
{
  while (true)
  {
    UserControlCodePlaceholderForTesting();
    setPower(driveMainLeft, vexRT[Ch3] / 127.);
    setPower(driveMainRight, vexRT[Ch2] / 127.);
    setPower(driveTetherLeft, vexRT[Ch3Xmtr2] / 127.);
    setPower(driveTetherRight, vexRT[Ch2Xmtr2] / 127.);
  }
}
